lineage-sdk: Remove sensitive_pn.xml from required
error: build/make/target/product/generic/Android.bp:1092:1: module "aosp_shared_system_image" variant "android_common": includes non-generic modules:
        "sensitive_pn.xml" from "org.lineageos.lib.phone",
Change-Id: I5199841366b8bf7f06fa212dc17fcbc4c636e5ca